//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATicketServerFW.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class showstarts
    {
        public string showname { get; set; }
        public string actor { get; set; }
        public Nullable<decimal> price { get; set; }
        public System.DateTime startime { get; set; }
        public string place { get; set; }
        public string url { get; set; }
        public string type { get; set; }
        public string front_image_path { get; set; }
        public Nullable<System.DateTime> readtime { get; set; }
    }
}
