//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowStart.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    
    public partial class cnblognews
    {
        public int id { get; set; }
        public string author { get; set; }
        public string watch { get; set; }
        public string comment { get; set; }
        public string favorite { get; set; }
        public string content { get; set; }
        public string url { get; set; }
        public string title { get; set; }
    }
}
