//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowStart.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class showstart
    {
        public long id { get; set; }
        public string showname { get; set; }
        public string actor { get; set; }
        public string price { get; set; }
        public string time { get; set; }
        public string place { get; set; }
        public string url { get; set; }
        public string type { get; set; }
        public Nullable<sbyte> StartOrEnd { get; set; }
        public Nullable<System.DateTime> ReadSessionTime { get; set; }
        public string front_image_path { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
    }
}
